### PR TITLE
Fixes #1

### LINKED ISSUE #1: Some components are not found
Hi, thanks for this fork!

I have tried to used this library with this setup.
Base template: https://github.com/wemake-services/wemake-vue-template

`testcafe.js`:

```js
import NuxtSelector from './testcafe-nuxt'

fixture('Getting Started')
  .page('http://localhost:3000')
  .beforeEach(async () => await NuxtSelector())

test('uses correct layout', async (t) => {
  const root = NuxtSelector()
  const rootVue = await root.getVue()

  await t.expect(root.exists).ok()
  await t.expect(rootVue.state.layoutName).eql('default')
})

test('all Comments are present', async (t) => {
  const comments = NuxtSelector('Comment')

  await t.expect(comments.count).eql(10)
})
```

Running: `nuxt build && testcafe chrome --app \"yarn start\" --app-init-delay 10000 testcafe.js`

## What happened

For some reason while doing it I was unable to find any `Comment` components.
I have forked your plugin to play around with it. I have found a problem inside this function:

```js
function getComponentTag (instance) {
            return (
        instance.$options.name ||
        instance.$options._componentTag ||
        instance.$options.__file ||
        ''
            );
}
```

Because `instance.$options.name` was always set to `'e'`. And `instance.$options._componentTag` had the desired `'comment'` name.

## Solution

As a result I have tweaked this function to work like so:

```js
    function getComponentTags (instance) {
      const candidates = [
        instance.$options.name,
        instance.$options._componentTag,
        instance.$options.__file
      ]

      return candidates.filter((e) => e) // filter out false values
    }

// ...
// Here's how I am calling it:
walkVueComponentNodes(root, 0, (node, tagIndex) => {
  return getComponentTags(node).indexOf(tags[tagIndex]) !== -1
})
```

And now it is working. @kartojal does it look good to you?
May I send a PR with this fix?

Related: https://github.com/wemake-services/wemake-vue-template/issues/504

### PR DESCRIPTION
**Pull request by sobolevn**
It is working for me:

```
 DONE  Compiled successfully in 12453ms                                 18:35:01

Hash: 68d067cdc98b1a9c33f9
Version: webpack 3.11.0
Time: 12453ms
                                  Asset       Size  Chunks             Chunk Names
layouts/default.95bdc81810aa235ca924.js  584 bytes       0  [emitted]  layouts/default
         vendor.38cf135a3c699826acff.js     254 kB       1  [emitted]  vendor
            app.7b6e41bc54f84d1a6d99.js    50.1 kB       2  [emitted]  app
       manifest.68d067cdc98b1a9c33f9.js    1.43 kB       3  [emitted]  manifest
                               LICENSES    1.65 kB          [emitted]  
 + 3 hidden assets
Webpack Bundle Analyzer saved report to /Users/sobolev/Desktop/wemake-vue-demo/.nuxt/dist/report.html
Hash: 6356ae1876f706bc13b1
Version: webpack 3.11.0
Time: 1577ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  184 kB          [emitted]  
  nuxt:build Building done +16s
 Running tests in:
 - Chrome 63.0.3239 / Mac OS X 10.11.6

 Getting Started
 ✓ nuxt uses correct layout
 ✓ all Comments are present


 2 passed (3s)
✨  Done in 44.00s.
```

Code:

```js
fixture('Getting Started')
  .page('http://localhost:3000')
  .beforeEach(async () => await RootNuxtSelector())

test('nuxt uses correct layout', async (t) => {
  const nuxt = RootNuxtSelector()
  const vm = await nuxt.getVue()

  await t.expect(nuxt.exists).ok()
  await t.expect(vm.state.layoutName).eql('default')
})

test('all Comments are present', async (t) => {
  const comments = RootNuxtSelector('Comment')
  const count = await comments.count

  await t.expect(count).eql(10)
})
```

### CODE REVIEW

**Comment by sobolevn** [comment]
Related: https://github.com/wemake-services/wemake-vue-template/issues/504

**Comment by sobolevn** [comment]
This is a blocking issue for me.

I would be really happy if you, @kartojal, could review and merge it.

**Comment by kartojal** [comment]
Does not pass tests for me, there is old dependencies too. Will make some cleaning and update packages. Meanwhile you can point your dependency to your forked repository in package.json file.

**Comment by sobolevn** [comment]
@kartojal anything that I can help you with?

**Comment by kartojal** [comment]
Merged! Now you can point to testcafe-nuxt-selectors@1.0.6 in your package.json file.

**Pull request merged**
